const http = require('http');
const url = require('url');

const server = http.createServer((req, res) => {
  const query = url.parse(req.url, true).query;
  const inputString = query.text || '';

  // JSON整形
  const jsonData = JSON.stringify({ text: inputString }, null, 2);
  
  // txtデータのレスポンスヘッダ
  res.writeHead(200, {
    'Content-Type': 'text/plain',
    'Content-Disposition': 'attachment; filename="formatted.txt"'
  });

  // txtデータのレスポンスボディ
  res.write(jsonData);
  res.end();
});

const port = 3000;
server.listen(port, () => {
  console.log(`Server running on port ${port}`);
});
